apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kibana
  namespace: logging
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kibana
    spec:
      containers:
      - image: 10.121.5.59:5000/fkhoda/kibana:5.4.0
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
status: {}
